version: '3.8'
services:
  ted-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /home/thomas/.ted-server:/root/.ted-server
    container_name: ted-server
