[project]
name = "ted"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.1",
    "pydantic>=2.12.4",
    "pyinstaller>=6.16.0",
    "pyyaml>=6.0.3",
]
